配列課題
AsukaKanematsu/php-array pull request #1
Opened 2023-04-13 15:49 UTC by AsukaKanematsu

## 作業対象

[作業をした教材のURL]
[https://www.notion.so/c4f781612e9a411ab616bef056fdac28?pvs=4#3581d89ddd7b4de7a4382a2d269fde3d](url)
[作成したページのURL(index.php)]
[http://localhost:8080/](url)

## 作業詳細

PHP基礎　配列の課題
for文で$iが1~10までループするたびに1づつ足す処理を書きましょう。
そして、ループするたび配列に$iを代入してください。
for文処理の終了後、配列の値の合計を出力
![index php - php-array - Visual Studio Code 2023_04_14 0_50_07](https://user-images.githubusercontent.com/129743465/231817709-71342721-d314-4304-a8ea-0bd260ab204a.png)

2023-04-14 08:22 UTC, KatsuyaTanaka95 requested changes
レビューさせていただきました！
ご修正をお願いいたします！🙆🙋😊

2023-04-14 08:22 UTC, KatsuyaTanaka95 commented on src/public/index.php
> +  $num[] += 1;
` $num[] += 1;`は、必要ないかと思いますので削除しちゃいましょう！！😊

2023-04-16 15:26 UTC, AsukaKanematsu commented
[PHP基礎] 配列

課題修正したのでお手隙の際確認お願いいたします。
![index php - php-array - Visual Studio Code 2023_04_14 0_50_07](https://user-images.githubusercontent.com/129743465/232323051-7b701361-2285-4f5c-a6fe-fb9a024af0f5.png)

2023-04-17 00:07 UTC, KatsuyaTanaka95 approved these changes
ご修正ありがとうございます！
LGTMです！！！
プルリクの修正依頼からの修正作業もなんなくできていて素晴らしいです！

mergeいただけると助かります！🙆🙋😊

2023-04-17 12:27 UTC, merged